version: '3.9'

services:
  php-env:
    build: .
    restart: unless-stopped
    volumes: 
      - ./:/var/www/html
    ports:
      - 6002:80
  
  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 6001:80
    environment:
      - PMA_ARBITRARY=1 



#docker-compose up --build 
#docker-compose exec app composer install ?? need to reed about this
#docker ps
#docker exec -it <container id> bask
  #ls
  #cat <file name>


